// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModuleTracker.EntityFramework;

#nullable disable

namespace ModuleTracker.EntityFramework.Migrations
{
    [DbContext(typeof(ModuleDbContext))]
    partial class ModuleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("ModuleTracker.EntityFramework.DTOs.ModuleDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("ModuleTracker.EntityFramework.DTOs.SheetDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModuleDtoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumOfExercises")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SheetNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ModuleDtoId");

                    b.ToTable("SheetDto");
                });

            modelBuilder.Entity("ModuleTracker.EntityFramework.DTOs.SheetDto", b =>
                {
                    b.HasOne("ModuleTracker.EntityFramework.DTOs.ModuleDto", null)
                        .WithMany("Sheets")
                        .HasForeignKey("ModuleDtoId");
                });

            modelBuilder.Entity("ModuleTracker.EntityFramework.DTOs.ModuleDto", b =>
                {
                    b.Navigation("Sheets");
                });
#pragma warning restore 612, 618
        }
    }
}
